baseURL: "https://Bingkun-Huang.github.io"
title: Bingkun HUANG
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags


params:
    description: "This website hosts Bingkun Huang's research papers, projects, course materials, data, curriculum vitae, and contact information."
    author: Bingkun Huang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Bingkun HUANG
        subtitle: "<br>➢ I am an MSc student in Mechatronics, Robotics and Biomechanical Engineering at the <b>Technical University of Munich</b>. I previously earned a B.Eng in the same field from <b>Bauman Moscow State Technical University</b>. <br><br> ➢ Currently, I am a student research assistant at <b>Munich Institute of Robotics and Machine Intelligence (MIRMI)</b>. <br> In parallel, I am also an Embedded Engineer at <b> Infineon Technologies</b>, focusing on robotics prototype development. My interests include Robot Motion Planning, Robot Learning, Robot D and Embedded System Design.<br><br> <b>[News]</b><br>  <small>• Submitted a paper to 17th World Symposium on the Algorithmic Foundations of Robotics (WAFR 2026). </small> <br>•  <small> a paper accepted to ICRA 2026. </small> <br><br><br>Thank you for visitng my webpage!"
        imageUrl: "bingkun.jpg"
        imageWidth: 200
    socialIcons:
        - name: Email
          url: mailto:bingkun.huang@tum.de
        - name: LinkedIn
          url: https://www.linkedin.com/in/bingkun-huang
        - name: GitHub
          url: https://github.com/Bingkun-Huang
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=-5xsb74AAAAJ&hl
        - name: Instagram
          url: https://www.instagram.com/_bingkun/
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
        text: "Bingkun HUANG"
        icon: favicon.ico
        iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
